# Composant (Beans) du module Patient
patientRepo         = ma.WhiteLab.repository.modules.patient.fileBase_implementation.PatientRepositoryImpl
patientService      = ma.WhiteLab.service.modules.patient.baseImplementation.PatientServiceImpl
patientController   = ma.WhiteLab.mvc.controllers.modules.patient.batch_implentation.PatientControllerImpl

# Composant (Beans) du module Cabinet
cabinetRepo         = ma.WhiteLab.repository.modules.cabinet.fileBase_implementation.CabinetRepositoryImpl
cabinetService      = ma.WhiteLab.service.modules.cabinet.baseImplementation.CabinetServiceImpl
cabinetController   = ma.WhiteLab.mvc.controllers.modules.cabinet.batch_implementation.CabinetControllerImpl

# Composant (Beans) du module Consultation
consultationRepo         = ma.WhiteLab.repository.modules.consultation.fileBase_implementation.ConsultationRepositoryImpl
consultationService      = ma.WhiteLab.service.modules.consultation.baseImplementation.ConsultationServiceImpl
consultationController   = ma.WhiteLab.mvc.controllers.modules.consultation.batch_implementation.ConsultationControllerImpl